In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
%matplotlib inline

In [2]:
#loading the data set into dataframe
df = pd.read_csv("E:/Datasets/ionosphere.csv")
df.head(10)

V1  V2       V3       V4       V5       V6       V7       V8       V9  \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
5   1   0  0.02337 -0.00592 -0.09924 -0.11949 -0.00763 -0.11824  0.14706   
6   1   0  0.97588 -0.10602  0.94601 -0.20800  0.92806 -0.28350  0.85996   
7   0   0  0.00000  0.00000  0.00000  0.00000  1.00000 -1.00000  0.00000   
8   1   0  0.96355 -0.07198  1.00000 -0.14333  1.00000 -0.21313  1.00000   
9   1   0 -0.01864 -0.08459  0.00000  0.00000  0.00000  0.00000  0.11470   

       V10  ...      V26      V27      V28      V29      V30      V31  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   
5  0.06637  ... -0.01535 -0.03240  0.09223 -0.07859  0.00732  0.00000   
6 -0.27342  ... -0.81634  0.13659 -0.82510  0.04606 -0.82395 -0.04262   
7  0.00000  ...  1.00000  1.00000  1.00000  0.00000  0.00000  1.00000   
8 -0.36174  ... -0.65440  0.57577 -0.69712  0.25435 -0.63919  0.45114   
9 -0.26810  ... -0.01326  0.20645 -0.02294  0.00000  0.00000  0.16595   

       V32      V33      V34  Class  
0 -0.54487  0.18641 -0.45300      1  
1 -0.06288 -0.13738 -0.02447      0  
2 -0.24180  0.56045 -0.38238      1  
3  1.00000 -0.32382  1.00000      0  
4 -0.59573 -0.04608 -0.65697      1  
5  0.00000 -0.00039  0.12011      0  
6 -0.81318 -0.13832 -0.80975      1  
7  1.00000  0.00000  0.00000      0  
8 -0.72779  0.38895 -0.73420      1  
9  0.24086 -0.08208  0.38065      0  

[10 rows x 35 columns]

In [3]:
df.shape

(351, 35)

In [4]:
#getting detail of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      351 non-null    int64  
 1   V2      351 non-null    int64  
 2   V3      351 non-null    float64
 3   V4      351 non-null    float64
 4   V5      351 non-null    float64
 5   V6      351 non-null    float64
 6   V7      351 non-null    float64
 7   V8      351 non-null    float64
 8   V9      351 non-null    float64
 9   V10     351 non-null    float64
 10  V11     351 non-null    float64
 11  V12     351 non-null    float64
 12  V13     351 non-null    float64
 13  V14     351 non-null    float64
 14  V15     351 non-null    float64
 15  V16     351 non-null    float64
 16  V17     351 non-null    float64
 17  V18     351 non-null    float64
 18  V19     351 non-null    float64
 19  V20     351 non-null    float64
 20  V21     351 non-null    float64
 21  V22     351 non-null    float64
 22  V2

In [5]:
#checking missing values
print(df.isnull().sum())    

V1       0
V2       0
V3       0
V4       0
V5       0
V6       0
V7       0
V8       0
V9       0
V10      0
V11      0
V12      0
V13      0
V14      0
V15      0
V16      0
V17      0
V18      0
V19      0
V20      0
V21      0
V22      0
V23      0
V24      0
V25      0
V26      0
V27      0
V28      0
V29      0
V30      0
V31      0
V32      0
V33      0
V34      0
Class    0
dtype: int64


In [6]:
# Rows containing duplicate data
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows:", duplicate_rows_df.shape)

number of duplicate rows: (1, 35)


In [7]:
df.describe()

V1     V2          V3          V4          V5          V6  \
count  351.000000  351.0  351.000000  351.000000  351.000000  351.000000   
mean     0.891738    0.0    0.641342    0.044372    0.601068    0.115889   
std      0.311155    0.0    0.497708    0.441435    0.519862    0.460810   
min      0.000000    0.0   -1.000000   -1.000000   -1.000000   -1.000000   
25%      1.000000    0.0    0.472135   -0.064735    0.412660   -0.024795   
50%      1.000000    0.0    0.871110    0.016310    0.809200    0.022800   
75%      1.000000    0.0    1.000000    0.194185    1.000000    0.334655   
max      1.000000    0.0    1.000000    1.000000    1.000000    1.000000   

               V7          V8          V9         V10  ...         V26  \
count  351.000000  351.000000  351.000000  351.000000  ...  351.000000   
mean     0.550095    0.119360    0.511848    0.181345  ...   -0.071187   
std      0.492654    0.520750    0.507066    0.483851  ...    0.508495   
min     -1.000000   -1.000000   -1.000000   -1.000000  ...   -1.000000   
25%      0.211310   -0.054840    0.087110   -0.048075  ...   -0.332390   
50%      0.728730    0.014710    0.684210    0.018290  ...   -0.015050   
75%      0.969240    0.445675    0.953240    0.534195  ...    0.156765   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

              V27         V28         V29         V30         V31         V32  \
count  351.000000  351.000000  351.000000  351.000000  351.000000  351.000000   
mean     0.541641   -0.069538    0.378445   -0.027907    0.352514   -0.003794   
std      0.516205    0.550025    0.575886    0.507974    0.571483    0.513574   
min     -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   
25%      0.286435   -0.443165    0.000000   -0.236885    0.000000   -0.242595   
50%      0.708240   -0.017690    0.496640    0.000000    0.442770    0.000000   
75%      0.999945    0.153535    0.883465    0.154075    0.857620    0.200120   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

              V33         V34       Class  
count  351.000000  351.000000  351.000000  
mean     0.349364    0.014480    0.641026  
std      0.522663    0.468337    0.480384  
min     -1.000000   -1.000000    0.000000  
25%      0.000000   -0.165350    0.000000  
50%      0.409560    0.000000    1.000000  
75%      0.813765    0.171660    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 35 columns]

In [8]:
#feature V2 seems to be redundant and we can drop it
df.drop('V2', axis=1, inplace=True)

In [9]:
df.head()

V1       V3       V4       V5       V6       V7       V8       V9      V10  \
0   1  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000  0.03760   
1   1  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000 -0.04549   
2   1  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965  0.01198   
3   1  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000  0.00000   
4   1  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152 -0.16399   

       V11  ...      V26      V27      V28      V29      V30      V31  \
0  0.85243  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1  0.50874  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.73082  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4  0.52798  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

       V32      V33      V34  Class  
0 -0.54487  0.18641 -0.45300      1  
1 -0.06288 -0.13738 -0.02447      0  
2 -0.24180  0.56045 -0.38238      1  
3  1.00000 -0.32382  1.00000      0  
4 -0.59573 -0.04608 -0.65697      1  

[5 rows x 34 columns]

In [10]:
#defining X and y from our dataset
X = df.drop("Class",axis=1)
X

V1       V3       V4       V5       V6       V7       V8       V9  \
0     1  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..      ...      ...      ...      ...      ...      ...      ...   
346   1  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

         V10      V11  ...      V25      V26      V27      V28      V29  \
0    0.03760  0.85243  ...  0.56811 -0.51171  0.41078 -0.46168  0.21266   
1   -0.04549  0.50874  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040   
2    0.01198  0.73082  ...  0.57528 -0.40220  0.58984 -0.22145  0.43100   
3    0.00000  0.00000  ...  1.00000  0.90695  0.51613  1.00000  1.00000   
4   -0.16399  0.52798  ...  0.03286 -0.65158  0.13290 -0.53206  0.02431   
..       ...      ...  ...      ...      ...      ...      ...      ...   
346 -0.04622  0.89391  ...  0.95378 -0.04202  0.83479  0.00123  1.00000   
347  0.01606  0.96510  ...  0.94520  0.01361  0.93522  0.04925  0.93159   
348  0.02446  0.94124  ...  0.93988  0.03193  0.92489  0.02542  0.92120   
349  0.00110  0.89724  ...  0.91050 -0.02099  0.89147 -0.07760  0.82983   
350 -0.09139  0.78735  ...  0.86467 -0.15114  0.81147 -0.04822  0.78207   

         V30      V31      V32      V33      V34  
0   -0.34090  0.42267 -0.54487  0.18641 -0.45300  
1   -0.11593 -0.16626 -0.06288 -0.13738 -0.02447  
2   -0.17365  0.60436 -0.24180  0.56045 -0.38238  
3   -0.20099  0.25682  1.00000 -0.32382  1.00000  
4   -0.62197 -0.05707 -0.59573 -0.04608 -0.65697  
..       ...      ...      ...      ...      ...  
346  0.12815  0.86660 -0.10714  0.90546 -0.04307  
347  0.08168  0.94066 -0.00035  0.91483  0.04712  
348  0.02242  0.92459  0.00442  0.92697 -0.00577  
349 -0.17238  0.96022 -0.03757  0.87403 -0.16243  
350 -0.00703  0.75747 -0.06678  0.85764 -0.06151  

[351 rows x 33 columns]

In [11]:
y = df['Class']

In [12]:
#generalize the dataset
from sklearn import preprocessing
X = preprocessing.MinMaxScaler().fit(X).transform(X)
X[0:5]

array([[1.      , 0.997695, 0.470555, 0.926215, 0.51153 , 0.91699 ,
        0.31146 , 1.      , 0.5188  , 0.926215, 0.411225, 0.798775,
        0.275275, 0.80268 , 0.308885, 0.92178 , 0.30729 , 0.79106 ,
        0.33904 , 0.784855, 0.35163 , 0.68473 , 0.263215, 0.784055,
        0.244145, 0.70539 , 0.26916 , 0.60633 , 0.32955 , 0.711335,
        0.227565, 0.593205, 0.2735  ],
       [1.      , 1.      , 0.405855, 0.965175, 0.31922 , 0.44566 ,
        0.032015, 1.      , 0.477255, 0.75437 , 0.161285, 0.67216 ,
        0.151465, 0.241575, 0.012425, 0.527495, 0.188815, 0.665545,
        0.      , 0.434245, 0.2735  , 0.40972 , 0.32133 , 0.39834 ,
        0.367155, 0.39766 , 0.407995, 0.4048  , 0.442035, 0.41687 ,
        0.46856 , 0.43131 , 0.487765],
       [1.      , 1.      , 0.483175, 1.      , 0.502425, 1.      ,
        0.43969 , 0.944825, 0.50599 , 0.86541 , 0.52673 , 0.927215,
        0.504135, 0.772955, 0.501495, 0.918875, 0.43178 , 0.877675,
        0.4573  , 0.854435, 0.36249 , 

In [13]:
#train and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=10, stratify=y)


In [14]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [15]:
predictions = LR.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
accuracy=confusion_matrix(y_test,predictions)
accuracy

array([[16,  9],
       [ 3, 43]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score
accuracy_s =accuracy_score(y_test,predictions)
accuracy_s

0.8309859154929577

In [18]:
predictions

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1], dtype=int64)

In [19]:
from sklearn.tree import DecisionTreeClassifier 
DCT = DecisionTreeClassifier()
DCT.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
predictions = DCT.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix
accuracy=confusion_matrix(y_test,predictions)
accuracy

array([[22,  3],
       [ 5, 41]], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_s =accuracy_score(y_test,predictions)
accuracy_s

0.8873239436619719

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.81      0.88      0.85        25
           1       0.93      0.89      0.91        46

    accuracy                           0.89        71
   macro avg       0.87      0.89      0.88        71
weighted avg       0.89      0.89      0.89        71



Ionopshere dataset contain "Class" as the feature label, containing binary values. Thus we can apply Classification Task under Supervised Learning. Applied Logistic Regression and Decision Tree Classifier, Logistic Regression is performing better. 